name: Chromatic

on: workflow_call

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-chromatic
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.ui-changes.outputs.all_changed_files }}
          ANY_CHANGED: ${{ steps.ui-changes.outputs.any_changed }}
        run: |
          echo "Found changed ${#ALL_CHANGED_FILES[@]} files"
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file"
          done
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: ./package.json
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run Visual Regression Tests
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: 'main'
          exitZeroOnChanges: true
          exitOnceUploaded: true
