name: 'CI checks'

on:
  pull_request:
    branches:
      - main

jobs:
  ui-changes:
    runs-on: ubuntu-latest
    name: ui-changes
    outputs:
      all_changed_files: ${{ steps.ui-changes.outputs.all_changed_files }}
      any_changed: ${{ steps.ui-changes.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            src/**
            !src/demo/**
            .storybook/**

  chromatic:
    name: Run Chromatic
    needs: [ui-changes]
    if: ${{ needs.ui-changes.outputs.any_changed == 'true' }}
    uses: ./.github/workflows/chromatic.yml
    secrets: inherit
